server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    password: 777441
    url: jdbc:mysql://localhost:3306/spring_services_customer_db
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
